version: 2.1

jobs:
  print-gpu:
    machine:
      image: linux-cuda-12:default
      resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - run:
          name: Print GPU Info
          command: nvidia-smi

workflows:
  gpu-info:
    jobs:
      - print-gpu
