version: 2.1

executors:
  gpu-executor:
    machine:
      image: linux-cuda-12:default
    resource_class: gpu.nvidia.medium

jobs:
  check-gpu:
    executor: gpu-executor
    steps:
      - checkout
      - run:
          name: Run nvidia-smi to check GPU
          command: nvidia-smi

workflows:
  gpu-check:
    jobs:
      - check-gpu
